options:
  loglevel:
    default: "Warn"
    type: string
    description: |
      How verbose you want your logging to be. See here for possible values:
      https://doc.rust-lang.org/log/log/enum.LogLevel.html
  backup-frequency:
    type: string
    default: "hourly"
    description: |
         How often to run backups.  Any valid crontab specification will work here. For more
         information please see man 5 cronttab
  backup-path:
    type: string
    default: "/mnt"
    description: "The path(s) to backup.  Multiple paths can be given with space separation"
  follow-symlimks:
    type: boolean
    default: true
    description: "Dereference symlinks and backup the path they are pointing to"
  ceph-source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:

        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main

      The last option should be used in conjunction with the key configuration
      option.

      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Ubuntu cloud archive.
  ceph-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
  gluster-source:
    type: string
    default: "ppa:gluster/glusterfs-3.8"
    description: |
      Optional configuration to support use of additional sources such as:

        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main

      The last option should be used in conjunction with the key configuration
      option.
  gluster-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
