#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'pip' 'pyudev')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

# Ensure that charmhelpers is installed
pip2 install charmhelpers
echo "Installing preserve snap"
snap install preserve --channel candidate

exec ./hooks/install.real
