#!/usr/bin/python
from charmhelpers.core.hookenv import action_get, action_set

__author__ = 'Chris Holcombe <chris.holcombe@canonical.com>'

import rados


# NOTE: This might not scale well.  If it doesn't we'll rewrite in Rust
def list_backups():
    action_get('backup-pool')
    action_get('namespace')
    cluster = rados.Rados(conffile='/etc/ceph/ceph.conf')
    cluster.connect()
    ioctx = cluster.open_ioctx('rbd')
    ioctx.set_namespace('b')
    object_iterator = ioctx.list_objects()
    backup_list = []
    while True:
        try:
            rados_object = object_iterator.next()
            backup_list.append(rados_object.key)
        except StopIteration:
            break
    ioctx.close()
    # Return to the user the list of backups
    action_set(
        {'backup_list': backup_list}
    )


if __name__ == '__main__':
    list_backups()
